### ISSUE TITLE
BUG REPORT: Error Messages Terminal freezing.

### ISSUE THREAD

**Issue by MrTrench** [darkplusplus/opentakrouter#26]
When user tries to interact with the terminal the program completely pauses. Connections still work but drop out every 30 seconds or so. .
the fix is to scroll all the way down in the terminal and backspace anything that was being typed into the terminal.

Repeating error until I manually fixed the terminal.
Suggestions is not to mess with terminal in any way if operating normally.

OpentakRouter v1.0.9 windows.

Example of error messages after the terminal caught up:

at dpp.opentakrouter.TakTcpPeer.OnReceived(Byte[] buffer, Int64 offset, Int64 size)
[17:47:19 INF] peer=dpp-public-tcp event=cot type=a-f-G-E-V-C
[17:47:19 ERR] peer=dpp-public-tcp type=unknown error=true forwarded=false
System.InvalidOperationException: There is an error in XML document (0, 0).
 ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderEvent.Read11_event()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at dpp.cot.Event.Parse(String payload)
   at dpp.cot.Message.Parse(Byte[] data, Int32 offset, Int32 length)
   at dpp.opentakrouter.TakTcpPeer.OnReceived(Byte[] buffer, Int64 offset, Int64 size)
[

**Comment by gregbuehler** [comment]
The hanging terminal thing is the result of something called "Quick Edit Mode" in Windows. When you select any text in the terminal it pauses the output to make it easier to select text. This has the unfortunate side effect of also pausing the running program. More discussion on the topic at https://stackoverflow.com/questions/33883530/why-is-my-command-prompt-freezing-on-windows-10.

For the error - I actually removed the default peering with the public instance. It was meant as a demonstrative configuration option only. This is resolved in https://github.com/darkplusplus/opentakrouter/pull/25 and contained in the default configuration for [v1.0.10](https://github.com/darkplusplus/opentakrouter/releases/tag/v1.0.10).
